const words = [
  {
    word: "Aberration",
    pos: "Noun",
    meaning: "A departure from what is normal or expected.",
    bangla: "স্বাভাবিক বা সাধারণ থেকে বিচ্যুতি।",
    example:
      "The sudden spike in temperature was an aberration for the region.",
  },
  {
    word: "Abeyance",
    pos: "Noun",
    meaning: "A temporary suspension or pause.",
    bangla: "স্থগিতাবস্থা বা সমাপ্তির অস্থায়ী বিরতি।",
    example: "The project was held in abeyance until funding became available.",
  },
  {
    word: "Acumen",
    pos: "Noun",
    meaning: "The ability to make good judgments and quick decisions.",
    bangla: "তীক্ষ্ণ বুদ্ধি বা বিচক্ষণতা।",
    example: "Her business acumen helped the startup grow quickly.",
  },
  {
    word: "Aegis",
    pos: "Noun",
    meaning: "Protection, sponsorship, or support.",
    bangla: "রক্ষা বা সহায়তা; আশ্রয়।",
    example: "The program was launched under the aegis of the ministry.",
  },
  {
    word: "Alacrity",
    pos: "Noun",
    meaning: "Brisk and cheerful readiness.",
    bangla: "উৎসাহী ও দ্রুত সাড়া বা ইচ্ছে।",
    example: "She accepted the invitation with alacrity.",
  },
  {
    word: "Ambiguity",
    pos: "Noun",
    meaning: "The quality of being open to more than one interpretation.",
    bangla: "অনির্দিষ্টতা; বহুমাত্রিক অর্থ থাকা।",
    example: "The ambiguity in his statement caused confusion.",
  },
  {
    word: "Anachronism",
    pos: "Noun",
    meaning: "Something placed in the wrong historical time.",
    bangla: "কালানুক্রমিক ভুল বা সময়োপযোগী নয় এমন বস্তু।",
    example: "The sword in the modern film was an anachronism.",
  },
  {
    word: "Anomaly",
    pos: "Noun",
    meaning: "Something that deviates from the norm.",
    bangla: "বিচ্যুতি; অনিয়ম।",
    example: "The scientist noticed an anomaly in the data.",
  },
  {
    word: "Antithesis",
    pos: "Noun",
    meaning: "A contrast or direct opposite.",
    bangla: "সম্পূর্ণ বিপরীত বা পরাঘাত।",
    example: "Her calm personality was the antithesis of his frantic energy.",
  },
  {
    word: "Apathy",
    pos: "Noun",
    meaning: "Lack of interest, enthusiasm, or concern.",
    bangla: "অবহেলা বা উদাসীনতা।",
    example: "Voter apathy led to a low turnout.",
  },
  {
    word: "Arbiter",
    pos: "Noun",
    meaning: "A person who settles disputes or has ultimate authority.",
    bangla: "বিচারক বা সিদ্ধান্তগ্রহীতা।",
    example: "The CEO acted as the arbiter in the dispute.",
  },
  {
    word: "Artifice",
    pos: "Noun",
    meaning: "Clever or cunning devices used to deceive.",
    bangla: "চাতুর্য বা কৌশল।",
    example: "The magician relied on artifice to fool the audience.",
  },
  {
    word: "Ascendancy",
    pos: "Noun",
    meaning: "Position of dominance or controlling influence.",
    bangla: "প্রভাব বা আধিপত্যের অবস্থান।",
    example: "The company sought ascendancy in the market.",
  },
  {
    word: "Aspiration",
    pos: "Noun",
    meaning: "A strong desire to achieve something.",
    bangla: "আকাঙ্ক্ষা বা উচ্চলক্ষ্যের ইচ্ছা।",
    example: "Her aspiration is to become a public health leader.",
  },
  {
    word: "Austerity",
    pos: "Noun",
    meaning:
      "Sternness or strictness in policy; economic measures to reduce spending.",
    bangla: "কঠোরতা বা কঠোর আর্থ-সামাজিক নীতি।",
    example: "The government introduced austerity to reduce the deficit.",
  },
  {
    word: "Autonomy",
    pos: "Noun",
    meaning: "Self-government or independence.",
    bangla: "স্বশাসন বা স্বাধীকার।",
    example: "The region was granted greater autonomy.",
  },
  {
    word: "Aversion",
    pos: "Noun",
    meaning: "A strong dislike or disinclination.",
    bangla: "অপ্রিয়তা বা বিরাগ।",
    example: "He has an aversion to loud music.",
  },
  {
    word: "Bastion",
    pos: "Noun",
    meaning: "A stronghold or fortress of protection.",
    bangla: "রক্ষার কেল্লা বা প্রতিরক্ষার কেন্দ্র।",
    example: "The university became a bastion of free speech.",
  },
  {
    word: "Bellwether",
    pos: "Noun",
    meaning: "An indicator or predictor of trends.",
    bangla: "প্রবণতা বা পরিবর্তনের নির্দেশক।",
    example: "Consumer sales are a bellwether for the economy.",
  },
  {
    word: "Benevolence",
    pos: "Noun",
    meaning: "Kindness or goodwill.",
    bangla: "দয়া বা দয়াশীলতা।",
    example: "Her benevolence was known throughout the neighborhood.",
  },
  {
    word: "Brevity",
    pos: "Noun",
    meaning: "Shortness of duration; conciseness.",
    bangla: "সংক্ষিপ্ততা বা সংক্ষিপ্ত বক্তব্য।",
    example: "The speech was notable for its brevity.",
  },
  {
    word: "Cadence",
    pos: "Noun",
    meaning: "A rhythmic flow of sound or movement.",
    bangla: "ছন্দ বা তাল।",
    example: "The poet's cadence carried the audience along.",
  },
  {
    word: "Calamity",
    pos: "Noun",
    meaning: "A disaster or great misfortune.",
    bangla: "বিপর্যয় বা মহা দুর্যোগ।",
    example: "The flood was a calamity for the coastal towns.",
  },
  {
    word: "Candor",
    pos: "Noun",
    meaning: "The quality of being open and honest.",
    bangla: "সত্যবাদিতা বা খোলামেলা আচরণ।",
    example: "I appreciated her candor during the interview.",
  },
  {
    word: "Capitulation",
    pos: "Noun",
    meaning: "The act of surrendering or yielding.",
    bangla: "হতাশা বা পরাজয় স্বীকার করা।",
    example: "The company's capitulation to pressure surprised investors.",
  },
  {
    word: "Catalyst",
    pos: "Noun",
    meaning: "Something that provokes significant change.",
    bangla: "উত্তেজক বা যে কারণে পরিবর্তন ঘটে।",
    example: "The new policy acted as a catalyst for reform.",
  },
  {
    word: "Censure",
    pos: "Noun",
    meaning: "Strong expression of disapproval (official).",
    bangla: "কঠোর নিন্দা বা সমালোচনা।",
    example: "The senator faced censure for his remarks.",
  },
  {
    word: "Chicanery",
    pos: "Noun",
    meaning: "Use of trickery or deception to achieve a goal.",
    bangla: "প্রতারণা বা কৌশল।",
    example: "The contract was full of legal chicanery.",
  },
  {
    word: "Cohesion",
    pos: "Noun",
    meaning: "The action of forming a united whole.",
    bangla: "একতা বা সংহততা।",
    example: "Strong leadership improved team cohesion.",
  },
  {
    word: "Collusion",
    pos: "Noun",
    meaning: "Secret cooperation for deceitful purposes.",
    bangla: "গোপন সঙ্গে মিলে প্রতারণা।",
    example: "The companies were accused of collusion to fix prices.",
  },
  {
    word: "Compendium",
    pos: "Noun",
    meaning: "A concise compilation of a body of knowledge.",
    bangla: "সংক্ষিপ্তসার বা সংকলন।",
    example: "The handbook is a useful compendium of grammar rules.",
  },
  {
    word: "Complicity",
    pos: "Noun",
    meaning: "Involvement in wrongdoing or a crime.",
    bangla: "অপরাধে অংশগ্রহণ বা যোগসাজশ।",
    example: "Her silence suggested complicity in the scheme.",
  },
  {
    word: "Conclave",
    pos: "Noun",
    meaning: "A private or secret meeting.",
    bangla: "গুপ্ত সভা বা সম্মেলন।",
    example: "The leaders met in a conclave to discuss strategy.",
  },
  {
    word: "Concurrence",
    pos: "Noun",
    meaning: "Agreement in opinion or action.",
    bangla: "সম্মতি বা একমত।",
    example: "There was concurrence on the team's plan.",
  },
  {
    word: "Conflagration",
    pos: "Noun",
    meaning: "A large, destructive fire.",
    bangla: "বৃহৎ অগ্নিকাণ্ড।",
    example: "The conflagration destroyed several blocks.",
  },
  {
    word: "Conjecture",
    pos: "Noun",
    meaning: "An opinion formed on incomplete evidence; a guess.",
    bangla: "অনুমান বা কল্পনা।",
    example: "The cause of the failure remains conjecture.",
  },
  {
    word: "Consensus",
    pos: "Noun",
    meaning: "General agreement among a group.",
    bangla: "সাধারণ সম্মতি।",
    example: "The committee reached a consensus after discussion.",
  },
  {
    word: "Constellation",
    pos: "Noun",
    meaning: "A grouping or cluster (literary: of ideas or people).",
    bangla: "সমষ্টি বা গুচ্ছ।",
    example: "A constellation of factors led to the policy change.",
  },
  {
    word: "Constraint",
    pos: "Noun",
    meaning: "A limitation or restriction.",
    bangla: "সীমাবদ্ধতা বা বাধা।",
    example: "Budget constraints limited the project's scope.",
  },
  {
    word: "Contempt",
    pos: "Noun",
    meaning: "The feeling that someone is beneath consideration or respect.",
    bangla: "অবজ্ঞা বা উপহাস।",
    example: "He spoke with contempt about the proposal.",
  },
  {
    word: "Contrivance",
    pos: "Noun",
    meaning: "A plan or device that is skillfully or cleverly created.",
    bangla: "কৌশল বা পরিকল্পনা।",
    example: "The plot relied too much on contrivance.",
  },
  {
    word: "Conundrum",
    pos: "Noun",
    meaning: "A confusing and difficult problem or question.",
    bangla: "জটিল সমস্যা বা ধাঁধা।",
    example: "The committee faced a conundrum over funding.",
  },
  {
    word: "Corroboration",
    pos: "Noun",
    meaning: "Evidence that confirms or supports a statement.",
    bangla: "প্রমাণ যা শক্তিশালী করে।",
    example: "The witness's testimony offered corroboration.",
  },
  {
    word: "Credence",
    pos: "Noun",
    meaning: "Belief in or acceptance of something as true.",
    bangla: "বিশ্বাস বা গ্রহণযোগ্যতা।",
    example: "The report gave credence to the scientist's claims.",
  },
  {
    word: "Criterion",
    pos: "Noun",
    meaning: "A standard by which things may be judged.",
    bangla: "মানদণ্ড বা বিচারবিধি।",
    example: "The selection committee used strict criteria.",
  },
  {
    word: "Culmination",
    pos: "Noun",
    meaning: "The highest or climactic point of something.",
    bangla: "চূড়ান্ত পর্যায় বা সমাপ্তি।",
    example: "The parade was the culmination of months of planning.",
  },
  {
    word: "Debacle",
    pos: "Noun",
    meaning: "A sudden and ignominious failure.",
    bangla: "বিপর্যয় বা বিশৃঙ্খলা।",
    example: "The product launch turned into a debacle.",
  },
  {
    word: "Debilitation",
    pos: "Noun",
    meaning: "The state of being weakened or made feeble.",
    bangla: "দুর্বলতা বা শক্তিহীনতা।",
    example: "The illness caused long-term debilitation.",
  },
  {
    word: "Deference",
    pos: "Noun",
    meaning: "Respectful submission or yielding to authority.",
    bangla: "শ্রদ্ধা বা নম্রতা।",
    example: "Out of deference to her elders, she remained silent.",
  },
  {
    word: "Deficit",
    pos: "Noun",
    meaning: "A shortfall in resources or funds.",
    bangla: "ঘাটতি বা অভাব।",
    example: "The budget deficit alarmed policymakers.",
  },
  {
    word: "Deliberation",
    pos: "Noun",
    meaning: "Careful consideration before decision.",
    bangla: "গুরুত্ব সহকারে চিন্তা বা আলোচনা।",
    example: "After much deliberation, they approved the plan.",
  },
  {
    word: "Denouement",
    pos: "Noun",
    meaning: "The final resolution of a narrative or situation.",
    bangla: "সমাপ্তি বা ফলাফল।",
    example: "The novel's denouement surprised many readers.",
  },
  {
    word: "Dereliction",
    pos: "Noun",
    meaning: "Willful neglect of duty or property.",
    bangla: "অবহেলা বা উপেক্ষা।",
    example: "The building fell into dereliction after years of neglect.",
  },
  {
    word: "Detriment",
    pos: "Noun",
    meaning: "Harm or damage.",
    bangla: "ক্ষতি বা অবনতি।",
    example: "His actions were to the detriment of the team.",
  },
  {
    word: "Dichotomy",
    pos: "Noun",
    meaning: "A division into two contrasting parts.",
    bangla: "বিভাজন বা দ্বৈততা।",
    example: "There is often a dichotomy between theory and practice.",
  },
  {
    word: "Dilemma",
    pos: "Noun",
    meaning: "A situation requiring a difficult choice.",
    bangla: "দ্বিধা বা কঠিন সিদ্ধান্ত।",
    example: "She faced a dilemma between career and family.",
  },
  {
    word: "Diligence",
    pos: "Noun",
    meaning: "Careful and persistent work or effort.",
    bangla: "পরিশ্রম ও সততা।",
    example: "Their diligence paid off with a successful trial.",
  },
  {
    word: "Discrepancy",
    pos: "Noun",
    meaning: "A lack of compatibility or similarity between facts.",
    bangla: "বৈপরীত্য বা অমিল।",
    example: "There was a discrepancy in the financial reports.",
  },
  {
    word: "Discourse",
    pos: "Noun",
    meaning: "Written or spoken communication or debate.",
    bangla: "আলোচনা বা বাক্যালাপ।",
    example: "The public discourse on climate change intensified.",
  },
  {
    word: "Disdain",
    pos: "Noun",
    meaning: "The feeling that someone or something is unworthy of respect.",
    bangla: "তুচ্ছ ভাব বা অবজ্ঞা।",
    example: "He treated the suggestion with disdain.",
  },
  {
    word: "Disparity",
    pos: "Noun",
    meaning: "A great difference or inequality.",
    bangla: "অসাম্য বা ফারাক।",
    example: "The disparity between regions was obvious.",
  },
  {
    word: "Dissemination",
    pos: "Noun",
    meaning: "The act of spreading widely (information, ideas).",
    bangla: "প্রচারণা বা বিস্তার।",
    example: "The dissemination of research findings is crucial.",
  },
  {
    word: "Dissonance",
    pos: "Noun",
    meaning: "Lack of harmony among elements; conflict.",
    bangla: "বৈসাদৃশ্য বা গোঁজাল।",
    example: "There was dissonance between policy and practice.",
  },
  {
    word: "Diversity",
    pos: "Noun",
    meaning: "Variety or difference within a group.",
    bangla: "বৈচিত্র্য বা বিভিন্নতা।",
    example: "The university values diversity in its student body.",
  },
  {
    word: "Divestiture",
    pos: "Noun",
    meaning:
      "The act of selling off subsidiary business interests or investments.",
    bangla: "সম্পত্তি বা অংশ বিক্রি করা।",
    example: "The divestiture of assets was announced.",
  },
  {
    word: "Domain",
    pos: "Noun",
    meaning: "An area of knowledge or activity.",
    bangla: "ক্ষেত্র বা বিষয়ভূমি।",
    example: "Economics falls within a broad domain of social science.",
  },
  {
    word: "Duress",
    pos: "Noun",
    meaning: "Pressure or coercion exerted to compel action.",
    bangla: "জবরদস্তি বা বাধ্যতা।",
    example: "He signed the contract under duress.",
  },
  {
    word: "Efficacy",
    pos: "Noun",
    meaning: "The ability to produce a desired result.",
    bangla: "কার্যকারিতা বা প্রভাব।",
    example: "The vaccine's efficacy was proven in trials.",
  },
  {
    word: "Elucidation",
    pos: "Noun",
    meaning: "Clarification or explanation.",
    bangla: "ব্যাখ্যা বা স্পষ্টকরণ।",
    example: "The professor offered an elucidation of the model.",
  },
  {
    word: "Empiricism",
    pos: "Noun",
    meaning: "The theory that knowledge comes from sensory experience.",
    bangla: "প্রযোজ্য অভিজ্ঞতার উপর ভিত্তি করে জ্ঞান অর্জন।",
    example: "The study emphasized empiricism over speculation.",
  },
  {
    word: "Enigma",
    pos: "Noun",
    meaning: "A mysterious person or thing; puzzle.",
    bangla: "রহস্য বা ধাঁধা।",
    example: "The origin of the artifact remains an enigma.",
  },
  {
    word: "Ennui",
    pos: "Noun",
    meaning:
      "A feeling of listlessness and dissatisfaction arising from lack of occupation.",
    bangla: "বিরক্তি বা অমনোযোগ।",
    example: "A sense of ennui had settled over the holidays.",
  },
  {
    word: "Entitlement",
    pos: "Noun",
    meaning: "A right to benefits or privileges.",
    bangla: "অধিকার বা দাবী।",
    example: "Citizens often have entitlement to basic services.",
  },
  {
    word: "Enumeration",
    pos: "Noun",
    meaning: "The action of counting or listing items.",
    bangla: "গণনা বা তালিকা করা।",
    example: "The enumeration of cases helped clarify the scope.",
  },
  {
    word: "Epiphany",
    pos: "Noun",
    meaning: "A sudden realization or insight.",
    bangla: "হৃদয়স্পর্শী হঠাৎ উপলব্ধি।",
    example: "She had an epiphany about her career direction.",
  },
  {
    word: "Epitome",
    pos: "Noun",
    meaning: "A person or thing that is a perfect example of a quality.",
    bangla: "সেরা উদাহরণ বা সারাংশ।",
    example: "He was the epitome of professionalism.",
  },
  {
    word: "Equilibrium",
    pos: "Noun",
    meaning: "A state of balance.",
    bangla: "সাম্য বা সমতুল্য অবস্থা।",
    example: "Markets reached an equilibrium after the rapid changes.",
  },
  {
    word: "Equity",
    pos: "Noun",
    meaning: "Fairness or justice in treatment.",
    bangla: "ন্যায্যতা বা সাম্য।",
    example: "The policy aimed to increase equity in education.",
  },
  {
    word: "Erudition",
    pos: "Noun",
    meaning: "Extensive knowledge acquired from reading and study.",
    bangla: "গভীর জ্ঞান বা পণ্ডিতত্ব।",
    example: "Her erudition was evident in every lecture.",
  },
  {
    word: "Escalation",
    pos: "Noun",
    meaning: "An increase in intensity or extent.",
    bangla: "বর্ধন বা উর্ধ্বগতি।",
    example: "The escalation of hostilities alarmed neighbors.",
  },
  {
    word: "Espousal",
    pos: "Noun",
    meaning: "The act of adopting or supporting a cause or belief.",
    bangla: "একটি ধারণা বা নীতিকে সমর্থন করা।",
    example: "The espousal of the policy changed public debate.",
  },
  {
    word: "Ethos",
    pos: "Noun",
    meaning: "The characteristic spirit or culture of a community.",
    bangla: "নৈতিকতা বা সাংস্কৃতিক ভাব।",
    example: "Academic ethos values inquiry and skepticism.",
  },
  {
    word: "Exacerbation",
    pos: "Noun",
    meaning: "An increase in severity or seriousness.",
    bangla: "তীব্রতা বৃদ্ধি বা অবনতি।",
    example: "Poor maintenance resulted in an exacerbation of the problem.",
  },
  {
    word: "Exigency",
    pos: "Noun",
    meaning: "An urgent need or demand.",
    bangla: "জরুরী প্রয়োজন বা দাবি।",
    example: "Responders prepared for the exigency of disaster relief.",
  },
  {
    word: "Exoneration",
    pos: "Noun",
    meaning: "The act of freeing someone from blame.",
    bangla: "অপরাধ থেকে মুক্তি বা অদোষ প্রমাণ।",
    example: "The new evidence led to his exoneration.",
  },
  {
    word: "Facet",
    pos: "Noun",
    meaning: "One aspect or side of something complex.",
    bangla: "পক্ষ বা দিক।",
    example: "Each facet of the issue required careful study.",
  },
  {
    word: "Fallacy",
    pos: "Noun",
    meaning: "A mistaken belief or error in reasoning.",
    bangla: "ভ্রান্ত ধারণা বা যুক্তির ত্রুটি।",
    example: "The argument rested on a basic fallacy.",
  },
  {
    word: "Fervor",
    pos: "Noun",
    meaning: "Intense and passionate feeling.",
    bangla: "উদ্দীপনা বা তীব্র আবেগ।",
    example: "The crowd reacted with fervor to the announcement.",
  },
  {
    word: "Fidelity",
    pos: "Noun",
    meaning: "Faithfulness or accuracy.",
    bangla: "বিশ্বস্ততা বা নির্ভুলতা।",
    example: "He proved his fidelity to the team's mission.",
  },
  {
    word: "Fluctuation",
    pos: "Noun",
    meaning: "Variation or irregular change.",
    bangla: "পরিবর্তন বা উঠানামা।",
    example: "Price fluctuations made planning difficult.",
  },
  {
    word: "Fortitude",
    pos: "Noun",
    meaning: "Courage in adversity.",
    bangla: "সহিষ্ণুতা বা সাহস।",
    example: "She faced the challenge with remarkable fortitude.",
  },
  {
    word: "Frivolity",
    pos: "Noun",
    meaning: "Lack of seriousness or sense.",
    bangla: "হালকাপনার কাজ বা সময় অপচয়।",
    example: "They criticized the proposals as mere frivolity.",
  },
  {
    word: "Futility",
    pos: "Noun",
    meaning: "Pointlessness or uselessness.",
    bangla: "বেকারত্ব বা অনর্থকতা।",
    example: "Attempts to reconcile proved futility after years of conflict.",
  },
  {
    word: "Gainsay",
    pos: "Noun",
    meaning: "Denial or contradiction (noun usage rare)",
    bangla: "অস্বীকার বা প্রত্যাখ্যান।",
    example: "There was no gainsay of the evidence.",
  },
  {
    word: "Gamut",
    pos: "Noun",
    meaning: "The complete range or scope of something.",
    bangla: "পরিসর বা সম্পূর্ণ পরিসরে।",
    example: "The festival covered the gamut of local arts.",
  },
  {
    word: "Gaucherie",
    pos: "Noun",
    meaning: "Lack of social grace or tact.",
    bangla: "অসামাজিকতা বা অদক্ষতা।",
    example: "His comment revealed a certain gaucherie.",
  },
  {
    word: "Genesis",
    pos: "Noun",
    meaning: "The origin or beginning of something.",
    bangla: "উৎপত্তি বা সৃষ্টি।",
    example: "The book traced the genesis of the movement.",
  },
  {
    word: "Gravitas",
    pos: "Noun",
    meaning: "Dignity, seriousness, or importance.",
    bangla: "গুরুত্ব বা মর্যাদা।",
    example: "She spoke with gravitas about policy reform.",
  },
  {
    word: "Hegemony",
    pos: "Noun",
    meaning: "Leadership or dominance, often by one group over others.",
    bangla: "প্রাধান্য বা আধিপত্য।",
    example: "The region sought to challenge the hegemony of the larger power.",
  },
  {
    word: "Hubris",
    pos: "Noun",
    meaning: "Excessive pride or self-confidence.",
    bangla: "অতিরিক্ত অহংকার।",
    example: "The CEO's hubris led to reckless decisions.",
  },
  {
    word: "Impetus",
    pos: "Noun",
    meaning: "A driving force or stimulus.",
    bangla: "প্রবণতা বা উদ্দীপক শক্তি।",
    example: "The grant provided new impetus for research.",
  },
  {
    word: "Impunity",
    pos: "Noun",
    meaning: "Exemption from punishment or loss.",
    bangla: "দোষমুক্তি বা শাস্তি ছাড়াই সুবিধা।",
    example: "Officials acted with virtual impunity.",
  },
  {
    word: "Incentive",
    pos: "Noun",
    meaning: "Something that motivates or encourages action.",
    bangla: "প্রেরণা বা প্রলোভন।",
    example: "Tax incentives were introduced to boost investment.",
  },
  {
    word: "Incidence",
    pos: "Noun",
    meaning: "The occurrence rate of something (e.g., disease).",
    bangla: "ঘটনার ঘটনা বা ঘটনার হার।",
    example: "There was a decline in the incidence of the illness.",
  },
  {
    word: "Inclination",
    pos: "Noun",
    meaning: "A natural tendency or preference.",
    bangla: "প্রবৃত্তি বা ঝোঁক।",
    example: "She showed an inclination toward public service.",
  },
  {
    word: "Indictment",
    pos: "Noun",
    meaning: "A formal charge or accusation of a serious crime.",
    bangla: "অভিযোগ বা আনুষ্ঠানিক দোষারোপ।",
    example: "The indictment shocked the industry.",
  },
  {
    word: "Indignation",
    pos: "Noun",
    meaning: "Anger at unfair treatment.",
    bangla: "অবিচারের বিরুদ্ধে রাগ বা আক্রোশ।",
    example: "The report provoked public indignation.",
  },
  {
    word: "Inequality",
    pos: "Noun",
    meaning: "The state of being unequal; disparity.",
    bangla: "অসমতা বা বৈষম্য।",
    example: "Economic inequality is a persistent challenge.",
  },
  {
    word: "Inference",
    pos: "Noun",
    meaning: "A conclusion drawn from evidence and reasoning.",
    bangla: "অনুমান বা সিদ্ধান্ত।",
    example: "His inference followed logically from the data.",
  },
  {
    word: "Infrastructure",
    pos: "Noun",
    meaning: "The basic physical systems and structures (roads, power, etc.).",
    bangla: "মৌলিক কাঠামো বা অবকাঠামো।",
    example: "The city invested heavily in infrastructure.",
  },
  {
    word: "Integrity",
    pos: "Noun",
    meaning: "Adherence to moral and ethical principles; honesty.",
    bangla: "সততা বা অখণ্ডতা।",
    example: "Her integrity earned widespread respect.",
  },
  {
    word: "Intervention",
    pos: "Noun",
    meaning: "The action of becoming involved to influence an outcome.",
    bangla: "হস্তক্ষেপ বা মধ্যস্থতা।",
    example: "The policy called for diplomatic intervention.",
  },
  {
    word: "Intrinsic",
    pos: "Noun",
    meaning:
      "Belonging naturally; essential (noun form: the intrinsic _nature_).",
    bangla: "স্বাভাবিক বা অভ্যন্তরীণ গুণ।",
    example: "Curiosity is intrinsic to human learning.",
  },
  {
    word: "Juncture",
    pos: "Noun",
    meaning: "A critical point in time; a crisis or choice point.",
    bangla: "সময় বা সিদ্ধান্ত গ্রহণের মুহূর্ত।",
    example: "At this juncture we must choose a new strategy.",
  },
  {
    word: "Kinship",
    pos: "Noun",
    meaning: "A connection or relationship, often by blood or shared values.",
    bangla: "সম্পর্ক বা আত্মীয়তা।",
    example: "They felt a kinship with the local community.",
  },
  {
    word: "Labyrinth",
    pos: "Noun",
    meaning: "A complex network of paths; a maze.",
    bangla: "জটিল পথ বা ধাঁধা।",
    example: "The novel's plot was a literary labyrinth.",
  },
  {
    word: "Lacuna",
    pos: "Noun",
    meaning: "An unfilled space or gap (e.g., in knowledge).",
    bangla: "শূন্যস্থান বা অভাব।",
    example: "There is a lacuna in the historical record.",
  },
  {
    word: "Lament",
    pos: "Noun",
    meaning: "An expression of sorrow or mourning (noun).",
    bangla: "শোক প্রকাশ বা খেদ।",
    example: "The loss was met with a public lament.",
  },
  {
    word: "Leverage",
    pos: "Noun",
    meaning: "The power to influence outcomes; financial gearing.",
    bangla: "প্রভাব বা সুবিধা।",
    example: "He used his connections as leverage during negotiations.",
  },
  {
    word: "Liaison",
    pos: "Noun",
    meaning: "A cooperative relationship facilitating communication.",
    bangla: "সমন্বয়কারী বা যোগাযোগকারী।",
    example: "The liaison between departments improved workflow.",
  },
  {
    word: "Litigation",
    pos: "Noun",
    meaning: "The process of taking legal action.",
    bangla: "বিচার কার্যক্রম বা মামলা।",
    example: "The company prepared for costly litigation.",
  },
  {
    word: "Magnanimity",
    pos: "Noun",
    meaning: "Generosity of spirit and forgiveness.",
    bangla: "মহানুভবতা বা উদারতা।",
    example: "She showed magnanimity toward her rivals.",
  },
  {
    word: "Malfeasance",
    pos: "Noun",
    meaning: "Wrongdoing, especially by a public official.",
    bangla: "দুর্নীতি বা অনৈতিক কাজ।",
    example: "The mayor faced accusations of malfeasance.",
  },
  {
    word: "Malaise",
    pos: "Noun",
    meaning: "A general feeling of discomfort or unease.",
    bangla: "অনাস্থা বা অস্বস্তি।",
    example: "A general malaise affected consumer confidence.",
  },
  {
    word: "Mandate",
    pos: "Noun",
    meaning: "An official order or authoritative command.",
    bangla: "আদেশ বা কর্তৃত্বমূলক নির্দেশ।",
    example: "The new government claimed a mandate for reform.",
  },
  {
    word: "Mediocrity",
    pos: "Noun",
    meaning: "The state of being average or ordinary; lack of excellence.",
    bangla: "সাধারণতা বা আপনতা।",
    example: "He refused to accept mediocrity in his work.",
  },
  {
    word: "Memento",
    pos: "Noun",
    meaning: "An object kept as a reminder of a person or event.",
    bangla: "স্মৃতিচিহ্ন বা স্মারক।",
    example: "She kept a memento from her grandmother.",
  },
  {
    word: "Modicum",
    pos: "Noun",
    meaning:
      "A small quantity of a particular thing, especially something desirable.",
    bangla: "সামান্য পরিমাণ।",
    example: "A modicum of patience would have helped.",
  },
  {
    word: "Abate",
    pos: "Verb",
    meaning: "To lessen in intensity or amount.",
    bangla: "কমে যাওয়া বা হ্রাস করা।",
    example: "The storm finally abated after midnight.",
  },
  {
    word: "Abdicate",
    pos: "Verb",
    meaning: "To give up a position of power or responsibility.",
    bangla: "অধিকার বা শক্তি ত্যাগ করা।",
    example: "The monarch decided to abdicate in favor of his son.",
  },
  {
    word: "Abjure",
    pos: "Verb",
    meaning: "To formally renounce a belief or claim.",
    bangla: "কোনো বিশ্বাস বা দাবী প্রত্যাখ্যান করা।",
    example: "He abjured his earlier statements under oath.",
  },
  {
    word: "Absolve",
    pos: "Verb",
    meaning: "To free someone from blame or obligation.",
    bangla: "দোষ বা দায়মুক্তি করা।",
    example: "The court absolved her of all charges.",
  },
  {
    word: "Abstain",
    pos: "Verb",
    meaning: "To choose not to do something, especially to vote.",
    bangla: "কোনো কাজ করতে বিরত থাকা।",
    example: "Several members decided to abstain from voting.",
  },
  {
    word: "Acclimatize",
    pos: "Verb",
    meaning: "To adapt to a new climate or conditions.",
    bangla: "নতুন পরিবেশে মানিয়ে নেওয়া।",
    example: "It took time to acclimatize to the high altitude.",
  },
  {
    word: "Accentuate",
    pos: "Verb",
    meaning: "To make something more noticeable or prominent.",
    bangla: "বৈশিষ্ট্য বেশি লক্ষণীয় করা।",
    example: "The director used lighting to accentuate the actor's face.",
  },
  {
    word: "Acquiesce",
    pos: "Verb",
    meaning: "To accept or comply passively or without protest.",
    bangla: "নির্বिरोधে বা নিঃশব্দে মেনে নেওয়া।",
    example: "She acquiesced to the committee's decision.",
  },
  {
    word: "Advocate",
    pos: "Verb",
    meaning: "To publicly support or recommend a cause or policy.",
    bangla: "সমর্থন করা বা উত্সাহিত করা।",
    example: "He advocates for renewable energy policies.",
  },
  {
    word: "Alleviate",
    pos: "Verb",
    meaning: "To make suffering or a problem less severe.",
    bangla: "কষ্ট বা সমস্যা হালকা করা।",
    example: "The medication helped alleviate the pain.",
  },
  {
    word: "Amalgamate",
    pos: "Verb",
    meaning: "To combine or unite to form one structure or organization.",
    bangla: "একত্রিত করা বা মিশ্রিত করা।",
    example: "They decided to amalgamate the two departments.",
  },
  {
    word: "Ameliorate",
    pos: "Verb",
    meaning: "To make something better or less bad.",
    bangla: "সংশ্লিষ্ট পরিস্থিতি উন্নত করা।",
    example: "Policies were introduced to ameliorate conditions.",
  },
  {
    word: "Annihilate",
    pos: "Verb",
    meaning: "To destroy completely.",
    bangla: "সম্পূর্ণভাবে ধ্বংস করা।",
    example: "The town was nearly annihilated by the earthquake.",
  },
  {
    word: "Arbitrate",
    pos: "Verb",
    meaning: "To settle a dispute through an impartial third party.",
    bangla: "একজন নিরপেক্ষ মাধ্যমে সিদ্ধান্ত গ্রহণ করা।",
    example: "They agreed to arbitrate their contractual dispute.",
  },
  {
    word: "Ascertain",
    pos: "Verb",
    meaning: "To find out or discover with certainty.",
    bangla: "নিশ্চিতভাবে খুঁজে বের করা।",
    example: "Investigators tried to ascertain the cause of the fire.",
  },
  {
    word: "Assuage",
    pos: "Verb",
    meaning: "To make an unpleasant feeling less intense.",
    bangla: "কষ্ট কমানো বা প্রশমিত করা।",
    example: "His apology did little to assuage her anger.",
  },
  {
    word: "Augment",
    pos: "Verb",
    meaning: "To make larger or increase.",
    bangla: "বৃদ্ধি করা বা বাড়ানো।",
    example: "They augmented their income with freelance work.",
  },
  {
    word: "Bolster",
    pos: "Verb",
    meaning: "To support or strengthen.",
    bangla: "সমর্থন বা শক্তিশালী করা।",
    example: "Good evidence will bolster the claim.",
  },
  {
    word: "Broach",
    pos: "Verb",
    meaning: "To bring up a subject for discussion.",
    bangla: "কোনো বিষয় উত্থাপন করা।",
    example: "She broached the topic carefully in the meeting.",
  },
  {
    word: "Capitulate",
    pos: "Verb",
    meaning: "To surrender or cease resisting.",
    bangla: "সমর্পণ করা বা অভিন্নতা মানা।",
    example: "The army had to capitulate after losing supplies.",
  },
  {
    word: "Castigate",
    pos: "Verb",
    meaning: "To reprimand or criticize severely.",
    bangla: "কঠোরভাবে সমালোচনা করা।",
    example: "The editor castigated the reporter for inaccuracies.",
  },
  {
    word: "Censure_2",
    pos: "Verb",
    meaning: "To express severe disapproval of someone or something.",
    bangla: "কঠোর নিন্দা প্রকাশ করা।",
    example: "The board censured the official for misconduct.",
  },
  {
    word: "Coalesce",
    pos: "Verb",
    meaning: "To come together to form one mass or whole.",
    bangla: "একত্রে মিলিত হওয়া।",
    example: "Different groups coalesced around a shared goal.",
  },
  {
    word: "Coerce",
    pos: "Verb",
    meaning: "To persuade by force or threats.",
    bangla: "জবরদস্তি করা বা চাপ দেওয়া।",
    example: "They were coerced into confessing.",
  },
  {
    word: "Commence",
    pos: "Verb",
    meaning: "To begin or start.",
    bangla: "শুরু করা।",
    example: "The ceremony will commence at noon.",
  },
  {
    word: "Compel",
    pos: "Verb",
    meaning: "To force someone to do something.",
    bangla: "দ্রুতি বা বাধ্য করা।",
    example: "Circumstances compelled her to resign.",
  },
  {
    word: "Comport",
    pos: "Verb",
    meaning: "To behave in a particular manner (usually 'comport oneself').",
    bangla: "প্রবৃত্তি প্রদর্শন করা।",
    example: "He comported himself with great dignity.",
  },
  {
    word: "Conceive",
    pos: "Verb",
    meaning: "To form an idea or concept in the mind.",
    bangla: "চিন্তায় গ্রহণ করা বা কল্পনা করা।",
    example: "She conceived a plan to improve the system.",
  },
  {
    word: "Conciliate",
    pos: "Verb",
    meaning: "To stop someone from being angry; placate.",
    bangla: "সন্তুষ্ট বা মীমাংসা করা।",
    example: "The manager tried to conciliate the upset staff.",
  },
  {
    word: "Concur",
    pos: "Verb",
    meaning: "To agree or have the same opinion.",
    bangla: "একমত হওয়া।",
    example: "Experts largely concur on the findings.",
  },
  {
    word: "Condone",
    pos: "Verb",
    meaning: "To accept or allow (behavior that is morally wrong).",
    bangla: "অবৈধ কেম্বলে অনুমতি দেয়া বা গ্রহণ করা।",
    example: "We cannot condone such unsafe practices.",
  },
  {
    word: "Confer",
    pos: "Verb",
    meaning: "To grant or bestow (a title, degree, benefit).",
    bangla: "প্রদান করা বা আর্ন্তকরণ করা।",
    example: "The university conferred an honorary degree.",
  },
  {
    word: "Confide",
    pos: "Verb",
    meaning: "To tell someone a secret or private matter.",
    bangla: "বিশ্বাস করে আত্মীয়কে বলা।",
    example: "She confided her worries to a close friend.",
  },
  {
    word: "Consolidate",
    pos: "Verb",
    meaning: "To combine into a single more effective whole.",
    bangla: "একত্রিত করে শক্তিশালী করা।",
    example: "They consolidated their positions into one office.",
  },
  {
    word: "Constitute",
    pos: "Verb",
    meaning: "To make up or form.",
    bangla: "গঠন করা বা স্থাপন করা।",
    example: "These elements constitute the bulk of the sample.",
  },
  {
    word: "Construe",
    pos: "Verb",
    meaning: "To interpret or understand in a particular way.",
    bangla: "ব্যাখ্যা করা বা অর্থ নির্ধারণ করা।",
    example: "His words could be construed as an apology.",
  },
  {
    word: "Contend",
    pos: "Verb",
    meaning: "To struggle to overcome or assert something.",
    bangla: "বক্তব্যে নির্দিষ্ট কিছু দাবি করা বা লড়াই করা।",
    example: "She contends that the new law will help.",
  },
  {
    word: "Contrive",
    pos: "Verb",
    meaning:
      "To plan with ingenuity; to bring about by deliberate use of skill.",
    bangla: "কৌশলে পরিকল্পনা করা।",
    example: "They contrived a scheme to reduce costs.",
  },
  {
    word: "Convene",
    pos: "Verb",
    meaning: "To come together for a meeting or activity.",
    bangla: "সমাবেশ করা বা ইভেন্ট সংগ্রহ করা।",
    example: "Leaders convened to discuss the crisis.",
  },
  {
    word: "Corroborate",
    pos: "Verb",
    meaning: "To confirm or support with evidence.",
    bangla: "প্রমাণ করে সমর্থন করা।",
    example: "The documents corroborated his account.",
  },
  {
    word: "Curtail",
    pos: "Verb",
    meaning: "To reduce or limit.",
    bangla: "সংকুচিত করা বা কাটা।",
    example: "The company curtailed travel to save costs.",
  },
  {
    word: "Delineate",
    pos: "Verb",
    meaning: "To describe or portray precisely.",
    bangla: "স্পষ্টভাবে বর্ণনা করা।",
    example: "The report delineates the policy's key features.",
  },
  {
    word: "Demur",
    pos: "Verb",
    meaning: "To raise doubts or show reluctance.",
    bangla: "অস্বীকৃতি জানানো বা দ্বিধা প্রকাশ করা।",
    example: "Some members demurred at the proposal.",
  },
  {
    word: "Denounce",
    pos: "Verb",
    meaning: "To publicly condemn or criticize.",
    bangla: "প্রচণ্ডভাবে নিন্দা করা।",
    example: "The government denounced the attack.",
  },
  {
    word: "Depict",
    pos: "Verb",
    meaning: "To describe in words or show in images.",
    bangla: "চিত্রায়িত করা বা বর্ণনা করা।",
    example: "The mural depicts local history.",
  },
  {
    word: "Deride",
    pos: "Verb",
    meaning: "To express contempt or ridicule.",
    bangla: "উপহাস করা বা নিন্দা করা।",
    example: "Critics derided the new plan as naive.",
  },
  {
    word: "Deter",
    pos: "Verb",
    meaning: "To discourage or prevent from acting.",
    bangla: "প্রতিহত বা বিরত রাখা।",
    example: "Stiff penalties deter reckless behavior.",
  },
  {
    word: "Deteriorate",
    pos: "Verb",
    meaning: "To become progressively worse.",
    bangla: "অবনতি ঘটে যাওয়া।",
    example: "Relations between the countries deteriorated.",
  },
  {
    word: "Devise",
    pos: "Verb",
    meaning: "To plan or invent by careful thought.",
    bangla: "পরিকল্পনা করা বা উদ্ভাবন করা।",
    example: "They devised a new testing method.",
  },
  {
    word: "Diminish",
    pos: "Verb",
    meaning: "To make or become less.",
    bangla: "হ্রাস করা বা কমে যাওয়া।",
    example: "The medicine diminished the symptoms.",
  },
  {
    word: "Discern",
    pos: "Verb",
    meaning: "To perceive or recognize clearly.",
    bangla: "ভেদ করা বা সনাক্ত করা।",
    example: "It was hard to discern the cause without tests.",
  },
  {
    word: "Disclose",
    pos: "Verb",
    meaning: "To make known or reveal.",
    bangla: "প্রকাশ করা বা উন্মোচন করা।",
    example: "The company disclosed the data breach.",
  },
  {
    word: "Discredit",
    pos: "Verb",
    meaning: "To harm the reputation or trustworthiness of.",
    bangla: "প্রতিষ্ঠা নষ্ট করা বা বিশ্বাস হারানো।",
    example: "The report discredited the earlier claims.",
  },
  {
    word: "Disparage",
    pos: "Verb",
    meaning: "To speak of in a derogatory manner.",
    bangla: "হীন করা বা নিন্দা করা।",
    example: "They disparaged his achievements unfairly.",
  },
  {
    word: "Disseminate",
    pos: "Verb",
    meaning: "To spread information widely.",
    bangla: "বিস্তৃতভাবে ছড়িয়ে দেয়া।",
    example: "The agency disseminated health guidelines.",
  },
  {
    word: "Dissuade",
    pos: "Verb",
    meaning: "To persuade someone not to take a course of action.",
    bangla: "বিরত রাখা বা পরামর্শে প্রত্যাহার করা।",
    example: "Friends tried to dissuade him from quitting.",
  },
  {
    word: "Distill",
    pos: "Verb",
    meaning: "To extract essential meaning or most important aspects.",
    bangla: "সংক্ষিপ্তভাবে উপস্থাপন করা।",
    example: "She distilled the complex theory into a few points.",
  },
  {
    word: "Diverge",
    pos: "Verb",
    meaning: "To separate from a path or opinion; to differ.",
    bangla: "পথ বা মত ভিন্ন হওয়া।",
    example: "Their views diverged on key issues.",
  },
  {
    word: "Divulge",
    pos: "Verb",
    meaning: "To reveal confidential information.",
    bangla: "প্রকাশ করা বা ফাঁস করা।",
    example: "He refused to divulge the source of the leak.",
  },
  {
    word: "Elicit",
    pos: "Verb",
    meaning: "To draw out a response or reaction.",
    bangla: "প্রতিক্রিয়া বা উত্তর আহরণ করা।",
    example: "Questions were used to elicit details from witnesses.",
  },
  {
    word: "Embellish",
    pos: "Verb",
    meaning: "To decorate or add details to make more attractive.",
    bangla: "অলঙ্করণ করা বা প্রসংশাময় ডিটেইল যোগ করা।",
    example: "The author embellished the story with anecdotes.",
  },
  {
    word: "Emulate",
    pos: "Verb",
    meaning: "To imitate with the aim of equaling or surpassing.",
    bangla: "অনুকরণ করা বা সবার চেয়ে ভাল করার চেষ্টা করা।",
    example: "Young athletes emulate their heroes.",
  },
  {
    word: "Endorse",
    pos: "Verb",
    meaning: "To publicly support or approve.",
    bangla: "সমর্থন করা বা অনুমোদন করা।",
    example: "Several leaders endorsed the initiative.",
  },
  {
    word: "Engender",
    pos: "Verb",
    meaning: "To cause or give rise to something.",
    bangla: "উৎপন্ন করা বা সৃষ্টি করা।",
    example: "The policy engendered widespread debate.",
  },
  {
    word: "Enhance",
    pos: "Verb",
    meaning: "To improve or increase in value or quality.",
    bangla: "উন্নত করা বা বৃদ্ধি করা।",
    example: "Training enhanced her technical skills.",
  },
  {
    word: "Enumerate",
    pos: "Verb",
    meaning: "To list or mention items one by one.",
    bangla: "তালিকা করা বা গোনা।",
    example: "The report enumerated several key failures.",
  },
  {
    word: "Epitomize",
    pos: "Verb",
    meaning: "To be a perfect example of something.",
    bangla: "চমৎকার উদাহরণ হিসেবে প্রদর্শিত হওয়া।",
    example: "The building epitomizes modern design.",
  },
  {
    word: "Espouse",
    pos: "Verb",
    meaning: "To adopt or support a cause, belief, or way of life.",
    bangla: "স্বীকার বা সমর্থন করা।",
    example: "He espoused progressive reform policies.",
  },
  {
    word: "Evince",
    pos: "Verb",
    meaning: "To reveal or show clearly.",
    bangla: "প্রমাণ করে দেখানো বা প্রকাশ করা।",
    example: "Her tone evinced no regret.",
  },
  {
    word: "Exacerbate",
    pos: "Verb",
    meaning: "To make a problem or situation worse.",
    bangla: "আরও খারাপ করে তোলা।",
    example: "Lack of funding exacerbated the crisis.",
  },
  {
    word: "Exculpate",
    pos: "Verb",
    meaning: "To free from blame or guilt.",
    bangla: "দোষমুক্ত করা বা নির্দোষ প্রমাণ করা।",
    example: "New evidence exculpated the defendant.",
  },
  {
    word: "Exemplify",
    pos: "Verb",
    meaning: "To illustrate or serve as an example of.",
    bangla: "উদাহরণ দিয়ে বোঝানো।",
    example: "This case exemplifies the dilemma of policymakers.",
  },
  {
    word: "Expedite",
    pos: "Verb",
    meaning: "To speed up the process or progress of something.",
    bangla: "দ্রুত করা বা ত্বরান্বিত করা।",
    example: "They expedited the shipment to meet demand.",
  },
  {
    word: "Explicate",
    pos: "Verb",
    meaning: "To explain in detail; to clarify meaning.",
    bangla: "বিস্তারিত ব্যাখ্যা করা।",
    example: "The paper explicated the complex theorem.",
  },
  {
    word: "Facilitate",
    pos: "Verb",
    meaning: "To make an action or process easier.",
    bangla: "সহজ করা বা সুবিধা প্রদান করা।",
    example: "A moderator was assigned to facilitate the discussion.",
  },
  {
    word: "Fathom",
    pos: "Verb",
    meaning: "To understand something after much thought.",
    bangla: "গভীরভাবে বোঝা বা অনুধাবন করা।",
    example: "Scientists struggled to fathom the anomaly.",
  },
  {
    word: "Foment",
    pos: "Verb",
    meaning: "To stir up or incite (usually trouble or dissent).",
    bangla: "উত্তেজিত করা বা উত্তেজনা সৃষ্টি করা।",
    example: "They were accused of fomenting unrest.",
  },
  {
    word: "Forbear",
    pos: "Verb",
    meaning: "To refrain from doing something; to be patient or tolerant.",
    bangla: "ধৈর্য ধারণ করা বা বিরত থাকা।",
    example: "He forbore from commenting on the verdict.",
  },
  {
    word: "Foster",
    pos: "Verb",
    meaning: "To encourage or promote development.",
    bangla: "উৎসাহিত করা বা উন্নত করা।",
    example: "Programs were designed to foster innovation.",
  },
  {
    word: "Gauge",
    pos: "Verb",
    meaning: "To measure or judge something.",
    bangla: "মূল্যায়ন করা বা পরিমাপ করা।",
    example: "We gauged customer interest with a survey.",
  },
  {
    word: "Garner",
    pos: "Verb",
    meaning:
      "To gather or collect (something, especially information or approval).",
    bangla: "সংগ্রহ করা বা আহরণ করা।",
    example: "The campaign garnered broad support.",
  },
  {
    word: "Glean",
    pos: "Verb",
    meaning: "To gather slowly and laboriously (often information).",
    bangla: "অল্প করে সংগ্রহ করা বা আহরণ করা।",
    example: "Researchers gleaned insights from archival sources.",
  },
  {
    word: "Hinder",
    pos: "Verb",
    meaning: "To create difficulties that delay progress.",
    bangla: "বাধা প্রদান করা বা বিলম্ব ঘটানো।",
    example: "Supply shortages hindered production.",
  },
  {
    word: "Hypothesize",
    pos: "Verb",
    meaning:
      "To propose a hypothesis or explanation as a starting point for investigation.",
    bangla: "অনুমান করে সুপারিশ করা।",
    example: "Scientists hypothesized a link between the variables.",
  },
  {
    word: "Illuminate",
    pos: "Verb",
    meaning: "To make something clear; to shed light on.",
    bangla: "প্রকাশ করা বা স্পষ্ট করা।",
    example: "The study illuminates new patterns in behavior.",
  },
  {
    word: "Imbue",
    pos: "Verb",
    meaning: "To fill someone or something with a quality or feeling.",
    bangla: "পূর্ণ করা বা অনুপ্রেরণা দেওয়া।",
    example: "Her writing is imbued with optimism.",
  },
  {
    word: "Impede",
    pos: "Verb",
    meaning: "To delay or prevent progress.",
    bangla: "বাধা সৃষ্টি করা বা প্রতিবন্ধকতা সৃষ্টি করা।",
    example: "Roadwork impeded traffic for hours.",
  },
  {
    word: "Imply",
    pos: "Verb",
    meaning: "To suggest or indicate without stating directly.",
    bangla: "ইঙ্গিত করা বা পরোক্ষভাবে বোঝানো।",
    example: "Her tone implied dissatisfaction.",
  },
  {
    word: "Implicate",
    pos: "Verb",
    meaning: "To show someone to be involved in a crime or wrongdoing.",
    bangla: "কোনো কাণ্ডে জড়িত প্রমাণ করা।",
    example: "The documents implicated several officials.",
  },
  {
    word: "Impugn",
    pos: "Verb",
    meaning: "To challenge or call into question (someone's integrity).",
    bangla: "প্রশ্নতীর্সাপ করা বা সন্দেহ প্রকাশ করা।",
    example: "Opponents sought to impugn his record.",
  },
  {
    word: "Indicate",
    pos: "Verb",
    meaning: "To point out or show evidence of something.",
    bangla: "ইঙ্গিত করা বা নির্দেশ করা।",
    example: "The markers indicate a rising trend.",
  },
  {
    word: "Induce",
    pos: "Verb",
    meaning: "To bring about or give rise to.",
    bangla: "উত্পন্ন করা বা উৎসাহিত করা।",
    example: "The drug can induce sleep in anxious patients.",
  },
  {
    word: "Infer",
    pos: "Verb",
    meaning: "To deduce or conclude information from evidence and reasoning.",
    bangla: "উপসংহারে পৌঁছানো।",
    example: "From the data we infer a correlation.",
  },
  {
    word: "Inhibit",
    pos: "Verb",
    meaning: "To restrain, hinder, or prevent an action or process.",
    bangla: "প্রতিহত করা বা বাধা প্রদান করা।",
    example: "Fear of reprisal inhibited whistleblowers.",
  },
  {
    word: "Innovate",
    pos: "Verb",
    meaning: "To introduce new methods, ideas, or products.",
    bangla: "নতুনকরণ করা বা উদ্ভাবন করা।",
    example: "Companies must innovate to remain competitive.",
  },
  {
    word: "Insinuate",
    pos: "Verb",
    meaning: "To suggest or hint (something bad) in an indirect way.",
    bangla: "পরোক্ষভাবে ইঙ্গিত করা।",
    example: "He insinuated that the report was biased.",
  },
  {
    word: "Instigate",
    pos: "Verb",
    meaning: "To bring about or initiate an action or event.",
    bangla: "প্ররোচিত করা বা শুরু করা।",
    example: "The protest was instigated by a local group.",
  },
  {
    word: "Integrate",
    pos: "Verb",
    meaning: "To combine things to operate as a whole.",
    bangla: "একত্রিত করা বা সংহত করা।",
    example: "The new features were integrated into the system.",
  },
  {
    word: "Interrogate",
    pos: "Verb",
    meaning: "To ask questions formally or aggressively.",
    bangla: "তৎপরভাবে বা কঠোরভাবে জিজ্ঞাসা করা।",
    example: "Officers interrogated witnesses thoroughly.",
  },
  {
    word: "Intervene",
    pos: "Verb",
    meaning: "To come between to alter a result or course.",
    bangla: "মধ্যস্থতা করা বা হস্তক্ষেপ করা।",
    example: "Authorities intervened to prevent escalation.",
  },
  {
    word: "Inundate",
    pos: "Verb",
    meaning: "To flood or overwhelm.",
    bangla: "প্ৰচুর পরিমাণে ঢেকে ফেলা বা অভিভূত করা।",
    example: "The phone lines were inundated with calls.",
  },
  {
    word: "Juxtapose",
    pos: "Verb",
    meaning: "To place side by side for contrast or comparison.",
    bangla: "পাশাপাশি বিশ্লেষণের জন্য রাখা।",
    example: "The exhibition juxtaposed classical and modern art.",
  },
  {
    word: "Legislate",
    pos: "Verb",
    meaning: "To make or enact laws.",
    bangla: "আইন প্রণয়ন করা।",
    example: "The parliament legislated new data privacy rules.",
  },
  {
    word: "Legitimize",
    pos: "Verb",
    meaning: "To make lawful or acceptable; to authorize.",
    bangla: "কানুনগতভাবে মান্য করা বা স্বীকৃতি দেওয়া।",
    example: "New guidelines aimed to legitimize the practice.",
  },
  {
    word: "Leverage_2",
    pos: "Verb",
    meaning: "To use something to maximum advantage.",
    bangla: "সর্বাধিক সুবিধা নেওয়ার জন্য ব্যবহার করা।",
    example: "They leveraged partnerships to expand distribution.",
  },
  {
    word: "Mitigate",
    pos: "Verb",
    meaning: "To make less severe or troublesome.",
    bangla: "হ্রাস করা বা শিথিল করা।",
    example: "Planting trees mitigates flood risk.",
  },
  {
    word: "Mollify",
    pos: "Verb",
    meaning: "To calm or soothe someone who is angry or upset.",
    bangla: "শান্ত করা বা প্রশমিত করা।",
    example: "The manager mollified upset employees with promises of review.",
  },
  {
    word: "Nullify",
    pos: "Verb",
    meaning: "To legally cancel or make void.",
    bangla: "অকার্যকর বা অবৈধ করা।",
    example: "The ruling nullified the earlier agreement.",
  },
  {
    word: "Obfuscate",
    pos: "Verb",
    meaning:
      "To deliberately make something unclear or difficult to understand.",
    bangla: "অস্পষ্ট বা জটিলভাবে করা।",
    example: "The dense language seemed designed to obfuscate the issue.",
  },
  {
    word: "Obviate",
    pos: "Verb",
    meaning: "To remove a need or difficulty; to prevent.",
    bangla: "প্রয়োজনীয়তা সরিয়ে ফেলা বা প্রতিরোধ করা।",
    example: "The vaccine obviated many previous concerns.",
  },
  {
    word: "Omit",
    pos: "Verb",
    meaning: "To leave out or exclude.",
    bangla: "বহিষ্কার করা বা বাদ দেওয়া।",
    example: "They omitted key details from the report.",
  },
  {
    word: "Optimize",
    pos: "Verb",
    meaning: "To make as effective, perfect, or useful as possible.",
    bangla: "সর্বোত্তম করা বা উন্নত করা।",
    example: "We optimized the workflow to save time.",
  },
  {
    word: "Oscillate",
    pos: "Verb",
    meaning: "To move or swing back and forth; to waver between choices.",
    bangla: "দুই অর্থে দোলায় থাকা বা দ্বিধায় থাকা।",
    example: "Public opinion oscillated during the debate.",
  },
  {
    word: "Permeate",
    pos: "Verb",
    meaning: "To spread throughout something; to pervade.",
    bangla: "পরিপূর্ণভাবে ছড়িয়ে পড়া।",
    example: "Doubt permeated the committee's discussions.",
  },
  {
    word: "Perpetuate",
    pos: "Verb",
    meaning: "To make something continue indefinitely.",
    bangla: "চিরস্থায়ী করা বা দীর্ঘস্থায়ী করা।",
    example: "The myth was perpetuated by repeated retellings.",
  },
  {
    word: "Peruse",
    pos: "Verb",
    meaning: "To read or examine carefully.",
    bangla: "বিস্তারিতভাবে পড়া বা পর্যালোচনা করা।",
    example: "She perused the contract before signing.",
  },
  {
    word: "Pervade",
    pos: "Verb",
    meaning: "To spread through every part of.",
    bangla: "পরিপূর্ণভাবে ছড়িয়ে পড়া।",
    example: "A sense of optimism pervaded the city.",
  },
  {
    word: "Placate",
    pos: "Verb",
    meaning: "To make someone less angry or hostile.",
    bangla: "শান্ত করা বা প্রশমিত করা।",
    example: "They tried to placate the protestors with concessions.",
  },
  {
    word: "Plummet",
    pos: "Verb",
    meaning: "To fall or drop straight down at high speed.",
    bangla: "হঠাৎ করে গড়িয়ে পড়া বা নিম্নগামী হওয়া।",
    example: "Stock prices plummeted after the news.",
  },
  {
    word: "Procrastinate",
    pos: "Verb",
    meaning: "To delay or postpone action.",
    bangla: "দেরি করা বা বিলম্ব করা।",
    example: "He tended to procrastinate on difficult tasks.",
  },
  {
    word: "Proliferate",
    pos: "Verb",
    meaning: "To increase rapidly in number; to spread.",
    bangla: "দ্রুত বৃদ্ধি পাওয়া বা ছড়িয়ে পড়া।",
    example: "Smart devices proliferated across households.",
  },
  {
    word: "Propagate",
    pos: "Verb",
    meaning: "To spread or promote an idea or species.",
    bangla: "প্রচারণা করা বা বংশবৃদ্ধি করা।",
    example: "The group propagated new environmental practices.",
  },
  {
    word: "Proscribe",
    pos: "Verb",
    meaning: "To forbid or condemn as harmful or illegal.",
    bangla: "নিষিদ্ধ করা বা অভিশংসিত করা।",
    example: "Certain substances were proscribed by law.",
  },
  {
    word: "Abstruse",
    pos: "Adjective",
    meaning: "Difficult to understand; obscure.",
    bangla: "অবোধগম্য বা গূঢ়।",
    example: "The theory is abstruse to those without training.",
  },
  {
    word: "Abject",
    pos: "Adjective",
    meaning: "Extremely bad, unpleasant, and degrading (also 'miserable').",
    bangla: "তীব্র কষ্টকর বা নিন্দনীয়।",
    example: "They lived in abject poverty.",
  },
  {
    word: "Acerbic",
    pos: "Adjective",
    meaning: "Sharp and forthright (often of a style of speech).",
    bangla: "কঠোর বা তীক্ষ্ণ (বক্তব্য)।",
    example: "Her acerbic remarks cut through the small talk.",
  },
  {
    word: "Adamant",
    pos: "Adjective",
    meaning: "Refusing to be persuaded or to change one's mind.",
    bangla: "অপ্রতিহত বা দৃঢ়প্রতিজ্ঞ।",
    example: "He was adamant that he would not resign.",
  },
  {
    word: "Aesthetic",
    pos: "Adjective",
    meaning: "Concerned with beauty or the appreciation of beauty.",
    bangla: "সৌন্দর্যবোধসম্পন্ন।",
    example: "The design choices were both practical and aesthetic.",
  },
  {
    word: "Altruistic",
    pos: "Adjective",
    meaning: "Showing selfless concern for the well-being of others.",
    bangla: "পরোপকারী বা দয়ালু।",
    example: "Her altruistic donation helped many families.",
  },
  {
    word: "Ambivalent",
    pos: "Adjective",
    meaning: "Having mixed feelings or contradictory ideas.",
    bangla: "বিকল্পধর্মী বা দ্বিধাগ্রস্ত।",
    example: "He felt ambivalent about the promotion.",
  },
  {
    word: "Amiable",
    pos: "Adjective",
    meaning: "Having a friendly and pleasant manner.",
    bangla: "সৌজন্যময় और সদয়।",
    example: "The new colleague proved amiable to everyone.",
  },
  {
    word: "Anomalous",
    pos: "Adjective",
    meaning: "Deviating from what is standard or expected.",
    bangla: "অসাধারণ বা অনিয়মী।",
    example: "The anomalous reading prompted further testing.",
  },
  {
    word: "Apathetic",
    pos: "Adjective",
    meaning: "Showing or feeling no interest or enthusiasm.",
    bangla: "উদাসীন বা অনাসক্ত।",
    example: "The audience remained apathetic during the speech.",
  },
  {
    word: "Assiduous",
    pos: "Adjective",
    meaning: "Showing great care and perseverance.",
    bangla: "মনোযোগী ও পরিশ্রমী।",
    example: "The student was assiduous in research.",
  },
  {
    word: "Auspicious",
    pos: "Adjective",
    meaning: "Conducive to success; favorable.",
    bangla: "শুভলক্ষণ বা সাফল্যবহ।",
    example: "The clear sky suggested an auspicious start.",
  },
  {
    word: "Autonomous",
    pos: "Adjective",
    meaning: "Independent and self-governing.",
    bangla: "স্বায়ত্তশাসিত বা স্বনির্ভর।",
    example: "The community manages several autonomous programs.",
  },
  {
    word: "Belligerent",
    pos: "Adjective",
    meaning: "Hostile and aggressive.",
    bangla: "আক্রমণাত্মক বা যুদ্ধাত্মক।",
    example: "His belligerent tone escalated the argument.",
  },
  {
    word: "Benign",
    pos: "Adjective",
    meaning: "Gentle and not harmful.",
    bangla: "নির্দোষ বা অনুহানিকর।",
    example: "The tumor was benign and easily treated.",
  },
  {
    word: "Bombastic",
    pos: "Adjective",
    meaning: "High-sounding but with little meaning; inflated.",
    bangla: "অতিরঞ্জিত ভাষা বা রসিক।",
    example: "The speech was bombastic but lacked substance.",
  },
  {
    word: "Brazen",
    pos: "Adjective",
    meaning: "Bold and without shame.",
    bangla: "নির্লজ্জ বা সাহসী।",
    example: "He made a brazen attempt to avoid taxes.",
  },
  {
    word: "Bucolic",
    pos: "Adjective",
    meaning: "Relating to the pleasant aspects of the countryside.",
    bangla: "গ্রামীন বা গ্রামের শান্ত সৌন্দর্যসূচক।",
    example: "They enjoyed the bucolic charm of the village.",
  },
  {
    word: "Capricious",
    pos: "Adjective",
    meaning: "Given to sudden and unaccountable changes of mood or behavior.",
    bangla: "খামখেয়ালী বা অনিশ্চিত।",
    example: "The weather in spring is notoriously capricious.",
  },
  {
    word: "Cathartic",
    pos: "Adjective",
    meaning:
      "Providing psychological relief through expression of strong emotions.",
    bangla: "সংহারাত্মক বা মুক্তিদায়ক।",
    example: "Writing the letter proved cathartic for her.",
  },
  {
    word: "Caustic",
    pos: "Adjective",
    meaning: "Sarcastic in a scathing and bitter way.",
    bangla: "তীক্ষ্ণ বা দাহ্যভাবে সমালোচনামূলক।",
    example: "His caustic comments offended many.",
  },
  {
    word: "Circumspect",
    pos: "Adjective",
    meaning: "Wary and unwilling to take risks.",
    bangla: "সাবধানী বা সতর্ক।",
    example: "They were circumspect in their investments.",
  },
  {
    word: "Coherent",
    pos: "Adjective",
    meaning: "Logical and consistent.",
    bangla: "সংগতিপূর্ণ বা যুক্তিযুক্ত।",
    example: "The argument was coherent and convincing.",
  },
  {
    word: "Conscientious",
    pos: "Adjective",
    meaning: "Wishing to do what is right; diligent and careful.",
    bangla: "প্রবুদ্ধ ও অধ্যবসায়ী।",
    example: "She was conscientious about meeting deadlines.",
  },
  {
    word: "Conspicuous",
    pos: "Adjective",
    meaning: "Clearly visible or attracting notice.",
    bangla: "চলমান বা লক্ষণীয়।",
    example: "The painting was conspicuous on the wall.",
  },
  {
    word: "Contentious",
    pos: "Adjective",
    meaning: "Causing or likely to cause disagreement or controversy.",
    bangla: "বিবাদিত বা বিতর্কের।",
    example: "The proposal became a contentious issue.",
  },
  {
    word: "Contrite",
    pos: "Adjective",
    meaning: "Feeling remorse or penitence; affected by guilt.",
    bangla: "অনুতপ্ত বা ক্ষমাপ্রার্থী।",
    example: "He offered a contrite apology for the mistake.",
  },
  {
    word: "Copious",
    pos: "Adjective",
    meaning: "Abundant in supply or quantity.",
    bangla: "প্রচুর বা বিস্তৃত।",
    example: "She took copious notes during the lecture.",
  },
  {
    word: "Cryptic",
    pos: "Adjective",
    meaning: "Having a meaning that is mysterious or obscure.",
    bangla: "রহস্যময় বা গূঢ়।",
    example: "He left a cryptic message on the desk.",
  },
  {
    word: "Cursory",
    pos: "Adjective",
    meaning: "Hasty and therefore not thorough or detailed.",
    bangla: "সারাংশমূলক বা তাত্ক্ষণিক।",
    example: "A cursory glance showed a few errors.",
  },
  {
    word: "Daunting",
    pos: "Adjective",
    meaning: "Seeming difficult to deal with in prospect; intimidating.",
    bangla: "ভীতিকর বা চ্যালেঞ্জিং।",
    example: "The task seemed daunting at first.",
  },
  {
    word: "Deleterious",
    pos: "Adjective",
    meaning: "Causing harm or damage.",
    bangla: "ক্ষতিকর বা হানিকারক।",
    example: "Pollution has deleterious effects on health.",
  },
  {
    word: "Derisive",
    pos: "Adjective",
    meaning: "Expressing contempt or ridicule.",
    bangla: "উপহাসসূচক বা তিরস্কারমূলক।",
    example: "He gave a derisive laugh at the suggestion.",
  },
  {
    word: "Desultory",
    pos: "Adjective",
    meaning: "Lacking a plan or purpose; unfocused.",
    bangla: "অবিচ্ছিন্ন বা উদ্দেশ্যহীন।",
    example: "Their conversation was desultory and wandering.",
  },
  {
    word: "Didactic",
    pos: "Adjective",
    meaning: "Intended to teach, particularly moral instruction.",
    bangla: "শিক্ষামূলক বা উপদেশমূলক।",
    example: "The lecture was informative but a bit didactic.",
  },
  {
    word: "Diminutive",
    pos: "Adjective",
    meaning: "Extremely small or tiny.",
    bangla: "ক্ষুদ্র বা লঘু।",
    example: "The kitten had a diminutive stature.",
  },
  {
    word: "Diplomatic",
    pos: "Adjective",
    meaning: "Having tact and skill in dealing with people.",
    bangla: "কূটনৈতিক বা সূক্ষ্ম কৌশলে সক্ষম।",
    example: "A diplomatic answer avoided further conflict.",
  },
  {
    word: "Discerning",
    pos: "Adjective",
    meaning: "Having good judgment or insight.",
    bangla: "বিচক্ষণ বা সূক্ষ্মবুদ্ধি সম্পন্ন।",
    example: "A discerning critic praised the film's subtleties.",
  },
  {
    word: "Discreet",
    pos: "Adjective",
    meaning: "Careful and prudent in speech or actions.",
    bangla: "বিবেচক বা গোপনীয়।",
    example: "They were discreet about the private matter.",
  },
  {
    word: "Dispassionate",
    pos: "Adjective",
    meaning: "Not influenced by strong emotion; impartial.",
    bangla: "নিরপেক্ষ বা উদাসীন।",
    example: "A dispassionate analysis is necessary for fairness.",
  },
  {
    word: "Dissonant",
    pos: "Adjective",
    meaning: "Lacking harmony; discordant.",
    bangla: "বৈসাদৃশ্যপূর্ণ বা বিশৃঙ্খল।",
    example: "The choir resolved the dissonant note quickly.",
  },
  {
    word: "Dubious",
    pos: "Adjective",
    meaning: "Hesitating or doubting; questionable.",
    bangla: "অনিশ্চিত বা সন্দেহজনক।",
    example: "She was dubious about the plan's success.",
  },
  {
    word: "Eccentric",
    pos: "Adjective",
    meaning: "Unconventional and slightly strange.",
    bangla: "অসমান্য বা অদ্ভুত।",
    example: "His eccentric habits amused his friends.",
  },
  {
    word: "Efficacious",
    pos: "Adjective",
    meaning: "Effective in producing the desired result.",
    bangla: "কার্যকর বা ফলপ্রসূ।",
    example: "The approach proved efficacious in trials.",
  },
  {
    word: "Egregious",
    pos: "Adjective",
    meaning: "Extremely bad and noticeable in a negative way.",
    bangla: "অত্যন্ত বর্বর বা খারাপ।",
    example: "The mistake was an egregious oversight.",
  },
  {
    word: "Eloquent",
    pos: "Adjective",
    meaning: "Fluent or persuasive in speaking or writing.",
    bangla: "প্রাঞ্জল বা বাকপটু।",
    example: "She gave an eloquent defense of the policy.",
  },
  {
    word: "Empirical",
    pos: "Adjective",
    meaning: "Based on observation or experiment rather than theory.",
    bangla: "প্রয়োগিক বা পরীক্ষানির্ভর।",
    example: "Empirical evidence supported the hypothesis.",
  },
  {
    word: "Enigmatic",
    pos: "Adjective",
    meaning: "Difficult to interpret or understand; mysterious.",
    bangla: "রহস্যময় বা বোঝা কঠিন।",
    example: "His enigmatic expression concealed his plans.",
  },
  {
    word: "Ephemeral",
    pos: "Adjective",
    meaning: "Lasting for a very short time.",
    bangla: "অল্প সময়ের জন্য স্থায়ী।",
    example: "Fashions can be ephemeral and quickly change.",
  },
  {
    word: "Equitable",
    pos: "Adjective",
    meaning: "Fair and impartial.",
    bangla: "ন্যায্য ও পক্ষপাতহীন।",
    example: "The reform aimed to create a more equitable system.",
  },
  {
    word: "Erratic",
    pos: "Adjective",
    meaning: "Unpredictable and inconsistent.",
    bangla: "অনিয়মিত বা অস্থির।",
    example: "The machine's erratic behavior required repair.",
  },
  {
    word: "Esoteric",
    pos: "Adjective",
    meaning: "Intended for or understood by a small, specialized audience.",
    bangla: "গুরুচরণীয় বা বিশেষজ্ঞদের জন্য।",
    example: "The theory remained esoteric outside academia.",
  },
  {
    word: "Ethical",
    pos: "Adjective",
    meaning: "Relating to moral principles; morally right.",
    bangla: "নৈতিক বা নৈতিকতামূলক।",
    example: "They debated the ethical implications of the study.",
  },
  {
    word: "Exemplary",
    pos: "Adjective",
    meaning: "Serving as a desirable model; commendable.",
    bangla: "উদাহরণীয় বা প্রশংসনীয়।",
    example: "Her professionalism was exemplary.",
  },
  {
    word: "Exorbitant",
    pos: "Adjective",
    meaning: "Unreasonably high (often of price or charge).",
    bangla: "অত্যধিক বা অযৌক্তিক।",
    example: "They charged an exorbitant fee for the service.",
  },
  {
    word: "Expeditious",
    pos: "Adjective",
    meaning: "Done with speed and efficiency.",
    bangla: "দ্রুত ও কার্যকর।",
    example: "An expeditious response reduced delays.",
  },
  {
    word: "Facetious",
    pos: "Adjective",
    meaning: "Treating serious issues with deliberately inappropriate humor.",
    bangla: "ঠাট্টাশ্রিত বা হাস্যরসপূর্ণ।",
    example: "His facetious comments were ill-timed.",
  },
  {
    word: "Fallacious",
    pos: "Adjective",
    meaning: "Based on a mistaken belief or unsound reasoning.",
    bangla: "ভ্রান্ত বা ত্রুটিপূর্ণ।",
    example: "The argument relied on a fallacious premise.",
  },
  {
    word: "Fastidious",
    pos: "Adjective",
    meaning: "Very attentive to detail; hard to please.",
    bangla: "খুঁতখুঁতে বা বিশদে যত্নশীল।",
    example: "A fastidious editor improved the manuscript's quality.",
  },
  {
    word: "Fervent",
    pos: "Adjective",
    meaning: "Having or displaying passionate intensity.",
    bangla: "উদ্দীপ্ত বা উত্সাহী।",
    example: "Her fervent support motivated volunteers.",
  },
  {
    word: "Flagrant",
    pos: "Adjective",
    meaning: "Obviously offensive or wrong.",
    bangla: "সরাসরি আপত্তিকর বা দোষারোপযোগ্য।",
    example: "The violation was a flagrant breach of rules.",
  },
  {
    word: "Flippant",
    pos: "Adjective",
    meaning: "Not showing a serious or respectful attitude.",
    bangla: "হালকাভাবে বা অবহেলাকরভাবে।",
    example: "His flippant response angered the committee.",
  },
  {
    word: "Fortuitous",
    pos: "Adjective",
    meaning: "Happening by chance, often with a beneficial result.",
    bangla: "সৌভাগ্যক্রমে সংগঠিত।",
    example: "Their meeting was fortuitous and led to collaboration.",
  },
  {
    word: "Fractious",
    pos: "Adjective",
    meaning: "Irritable and quarrelsome.",
    bangla: "একগুঁয়ে বা অশান্ত।",
    example: "The fractious crowd interrupted the speaker.",
  },
  {
    word: "Frugal",
    pos: "Adjective",
    meaning: "Sparing or economical with resources.",
    bangla: "সঞ্চয়ী বা মিতব্যয়ী।",
    example: "They maintained a frugal household to save for education.",
  },
  {
    word: "Garrulous",
    pos: "Adjective",
    meaning: "Excessively talkative, especially on trivial matters.",
    bangla: "বাকপটু বা বকবক করা।",
    example: "The garrulous guide monopolized the conversation.",
  },
  {
    word: "Gregarious",
    pos: "Adjective",
    meaning: "Fond of company; sociable.",
    bangla: "সামাজিক বা মিলনসার।",
    example: "Gregarious students formed study groups easily.",
  },
  {
    word: "Haughty",
    pos: "Adjective",
    meaning: "Arrogantly superior and disdainful.",
    bangla: "গর্বিত বা বদভ্যাসপূর্ণ।",
    example: "His haughty manner alienated colleagues.",
  },
  {
    word: "Hedonistic",
    pos: "Adjective",
    meaning: "Engaged in the pursuit of pleasure; self-indulgent.",
    bangla: "আনন্দপ্রিয় বা ভোগবাদী।",
    example: "A hedonistic lifestyle often ignores long-term costs.",
  },
  {
    word: "Hesitant",
    pos: "Adjective",
    meaning: "Tentative or unsure in action or speech.",
    bangla: "দ্বিধাদ্বন্দ্বপূর্ণ বা অনিশ্চিত।",
    example: "She was hesitant to answer without more information.",
  },
  {
    word: "Iconoclastic",
    pos: "Adjective",
    meaning: "Attacking or challenging established beliefs or institutions.",
    bangla: "প্রচলিত বিশ্বাস ভাঙিয়ে দেয় এমন।",
    example: "The author's iconoclastic views sparked debate.",
  },
  {
    word: "Idiosyncratic",
    pos: "Adjective",
    meaning: "Peculiar to an individual; quirky.",
    bangla: "স্বকীয় বা অনন্য বৈশিষ্ট্যের।",
    example: "Her idiosyncratic method produced surprising results.",
  },
  {
    word: "Impassive",
    pos: "Adjective",
    meaning: "Not showing emotion; calm and serene.",
    bangla: "অবিচল বা নিরবে।",
    example: "He remained impassive during the accusations.",
  },
  {
    word: "Impeccable",
    pos: "Adjective",
    meaning: "Without fault; perfect in behavior or appearance.",
    bangla: "ত্রুটিহীন বা নিখুঁত।",
    example: "Her credentials were impeccable for the role.",
  },
  {
    word: "Impetuous",
    pos: "Adjective",
    meaning: "Acting quickly without careful thought; impulsive.",
    bangla: "হঠাৎ কর্মপরায়ণ বা অনিচ্ছুকভাবে কার্যকর।",
    example: "An impetuous decision led to regret later.",
  },
  {
    word: "Implicit",
    pos: "Adjective",
    meaning: "Implied though not plainly expressed.",
    bangla: "পরোক্ষ বা অপ্রকাশিত।",
    example: "There was an implicit agreement to cooperate.",
  },
  {
    word: "Incisive",
    pos: "Adjective",
    meaning: "Intelligently analytical and clear-thinking.",
    bangla: "তীক্ষ্ণ বা স্পষ্টভাবে বিশ্লেষণাত্মক।",
    example: "Her incisive questions revealed key issues.",
  },
  {
    word: "Indolent",
    pos: "Adjective",
    meaning: "Wanting to avoid activity; lazy.",
    bangla: "অলস বা কাজ এড়ানো প্রবণ।",
    example: "An indolent approach slowed the project's progress.",
  },
  {
    word: "Ineffable",
    pos: "Adjective",
    meaning: "Too great to be expressed in words; indescribable.",
    bangla: "অবর্ণনীয় বা বর্ণনা করা সম্ভব নয়।",
    example: "The view from the mountain was ineffable.",
  },
  {
    word: "Inimical",
    pos: "Adjective",
    meaning: "Tending to obstruct or harm; unfriendly.",
    bangla: "ক্ষতিকর বা শত্রুভাবাপন্ন।",
    example: "Policies inimical to innovation were repealed.",
  },
  {
    word: "Innocuous",
    pos: "Adjective",
    meaning: "Not harmful or offensive.",
    bangla: "নিরীহ বা ক্ষতিকর নয়।",
    example: "The comment was innocuous but misinterpreted.",
  },
  {
    word: "Insidious",
    pos: "Adjective",
    meaning: "Proceeding in a gradual, subtle way but with harmful effects.",
    bangla: "ধীরে ধীরে ক্ষতিকর প্রভাব ফেলে এমন।",
    example: "The disease had an insidious onset.",
  },
  {
    word: "Insular",
    pos: "Adjective",
    meaning: "Narrow-minded or isolated in outlook.",
    bangla: "দ্বীপীয় বা বিচ্ছিন্ন ভাবাপন্ন।",
    example: "An insular attitude limited their collaborations.",
  },
  {
    word: "Intrepid",
    pos: "Adjective",
    meaning: "Fearless and adventurous.",
    bangla: "নির্ভীক বা সাহসী।",
    example: "The intrepid explorer traversed remote regions.",
  },
  {
    word: "Invaluable",
    pos: "Adjective",
    meaning: "Extremely useful or indispensable.",
    bangla: "অমূল্য বা অপরিহার্য।",
    example: "Her guidance proved invaluable during the crisis.",
  },
  {
    word: "Laconic",
    pos: "Adjective",
    meaning: "Using very few words; concise to the point of seeming rude.",
    bangla: "সংক্ষিপ্ত বা কথামিতির।",
    example: "His laconic reply gave nothing away.",
  },
  {
    word: "Languid",
    pos: "Adjective",
    meaning: "Displaying a lack of energy or enthusiasm; slow.",
    bangla: "বিরক্ত বা অনাশ্রিত।",
    example: "The heat made everyone's step languid.",
  },
  {
    word: "Latent",
    pos: "Adjective",
    meaning: "Existing but not yet developed or manifest; hidden.",
    bangla: "লুপ্ত বা আড়ালভাগে থাকা।",
    example: "The latent potential in the technology was enormous.",
  },
  {
    word: "Laudable",
    pos: "Adjective",
    meaning: "Deserving praise and commendation.",
    bangla: "প্রশংসনীয় বা কৃতজ্ঞতার যোগ্য।",
    example: "Their laudable efforts reduced waste.",
  },
  {
    word: "Lethargic",
    pos: "Adjective",
    meaning: "Lacking energy; sluggish.",
    bangla: "জড় বা অলস।",
    example: "He felt lethargic after the long meeting.",
  },
  {
    word: "Loquacious",
    pos: "Adjective",
    meaning: "Tending to talk a great deal; talkative.",
    bangla: "বক্তব্যপ্রিয় বা বাকপটু।",
    example: "The loquacious host filled the time with anecdotes.",
  },
  {
    word: "Lucid",
    pos: "Adjective",
    meaning: "Expressed clearly; easy to understand.",
    bangla: "স্পষ্ট বা বোধগম্য।",
    example: "Her explanation of the concept was lucid.",
  },
  {
    word: "Diligently",
    pos: "Adverb",
    meaning: "With careful and persistent effort.",
    bangla: "অধ্যবসায় ও যত্ন সহকারে।",
    example: "She worked diligently to finish the report on time.",
  },
  {
    word: "Meticulously",
    pos: "Adverb",
    meaning: "In a way that shows great attention to detail.",
    bangla: "অত্যন্ত যত্ন সহকারে।",
    example: "He meticulously checked every figure in the spreadsheet.",
  },
  {
    word: "Sporadically",
    pos: "Adverb",
    meaning: "Occasionally, at irregular intervals.",
    bangla: "অনিয়মিতভাবে বা মাঝে মধ্যে।",
    example: "It rained sporadically throughout the afternoon.",
  },
  {
    word: "Unequivocally",
    pos: "Adverb",
    meaning: "In a way that leaves no doubt; clearly and unambiguously.",
    bangla: "স্পষ্টভাবে বা নির্দ্বিধায়।",
    example: "She unequivocally denied the rumor.",
  },
  {
    word: "Assiduously",
    pos: "Adverb",
    meaning: "With great care and perseverance.",
    bangla: "অধ্যবসায়ীভাবে।",
    example: "They worked assiduously to meet the deadline.",
  },
  {
    word: "Adamantly",
    pos: "Adverb",
    meaning: "Firmly and resolutely; in a way that refuses to be persuaded.",
    bangla: "দৃঢ়ভাবে বা অটলভাবে।",
    example: "He adamantly refused the offer.",
  },
  {
    word: "Eloquently",
    pos: "Adverb",
    meaning: "In a fluent and persuasive manner.",
    bangla: "প্রাঞ্জলভাবে বা বাকপটুতা সহ।",
    example: "The speaker argued eloquently for reform.",
  },
  {
    word: "Explicitly",
    pos: "Adverb",
    meaning: "In a clear and detailed manner, leaving no room for confusion.",
    bangla: "স্পষ্টভাবে বা পরিষ্কারভাবে।",
    example: "The instructions were explicitly stated in the manual.",
  },
  {
    word: "Indiscriminately",
    pos: "Adverb",
    meaning: "Without careful distinction or choice; randomly.",
    bangla: "বাছাই ছাড়া বা নির্বিচারে।",
    example: "The policy affected residents indiscriminately.",
  },
  {
    word: "Intrinsically",
    pos: "Adverb",
    meaning: "In an essential or natural way.",
    bangla: "আভ্যন্তরীণভাবে বা মূলত।",
    example: "The task is intrinsically valuable.",
  },
  {
    word: "Ostensibly",
    pos: "Adverb",
    meaning: "Stated or appearing to be true, but not necessarily so.",
    bangla: "প্রকাশ্যভাবে বা বাহ্যিকভাবে।",
    example: "He was ostensibly helpful but had ulterior motives.",
  },
  {
    word: "Perfunctorily",
    pos: "Adverb",
    meaning: "Done with minimal effort or reflection; superficially.",
    bangla: "আড়ম্বরহীনভাবে বা নীরসভাবে।",
    example: "She inspected the work perfunctorily and moved on.",
  },
  {
    word: "Reluctantly",
    pos: "Adverb",
    meaning: "In an unwilling or hesitant way.",
    bangla: "অনিচ্ছায় বা দ্বিধাসহ।",
    example: "He reluctantly agreed to lend his support.",
  },
  {
    word: "Strenuously",
    pos: "Adverb",
    meaning: "With great effort or exertion.",
    bangla: "প্রচণ্ডভাবে বা কঠোরভাবে।",
    example: "They worked strenuously to complete the renovation.",
  },
  {
    word: "Tentatively",
    pos: "Adverb",
    meaning: "Subject to further confirmation; not definite.",
    bangla: "প্রায়শই পরীক্ষামূলক বা অনিশ্চিতভাবে।",
    example: "They tentatively scheduled the meeting for Tuesday.",
  },
  {
    word: "Uneasily",
    pos: "Adverb",
    meaning: "With discomfort or anxiety; in an uneasy manner.",
    bangla: "অস্বস্তিতে বা চিন্তায়।",
    example: "He shifted uneasily during the awkward silence.",
  },
  {
    word: "Vigorously",
    pos: "Adverb",
    meaning: "With forceful energy; forcefully and energetically.",
    bangla: "উৎসাহভরে বা বলবৎভাবে।",
    example: "Critics responded vigorously to the proposal.",
  },
  {
    word: "Zealously",
    pos: "Adverb",
    meaning:
      "With great energy or enthusiasm in pursuit of a cause or objective.",
    bangla: "উৎসাহ উদ্দীপনায়।",
    example: "Volunteers worked zealously for the relief effort.",
  },
];
